### ISSUE TITLE
Lint check problem

### ISSUE THREAD

**Issue by rehayes** [NXP/i3c-slave-design#1]
Lint check on line #154 of file i3c_autonomous.v has a size mismatch.
As is:
assign is_valid[i] = is_writable | is_readable;
I believe this should be:
assign is_valid[i] = is_writable[i] | is_readable[i];

There are other lint size mismatchs mostly related to assignments of "0".

**Comment by pkimelman-nxp** [comment]
Sorry, I did not reply. You are correct and  that was fixed in the updates. Thanks for the feedback.
