### ISSUE TITLE
I3C Clock frequency

### ISSUE THREAD

**Issue by prats2018** [NXP/i3c-slave-design#12]
Hi
As per MIPI I3C specification, what are the supported SCL frequencies?

Thanks
Prats

**Comment by pkimelman-nxp** [comment]
I3C supports up to 12.5MHz (with margin added).

On Jul 23, 2019, at 11:33 PM, prats2018 <notifications@github.com<mailto:notifications@github.com>> wrote:


Caution: EXT Email

Hi
As per MIPI I3C specification, what are the supported SCL frequencies?

Thanks
Prats

—
