### ISSUE TITLE
sda_pad_oe

### ISSUE THREAD

**Issue by Jiahua-Gong** [NXP/i3c-slave-design#15]
# Using the  I3C_auton_wrap_full module as the rtl top. 
#  the testcase as follow steps
## 4.  testbeach send scl,The Dut sda_pad_oe control may have a error direction.

The simulation wave as follows.
![image](https://user-images.githubusercontent.com/33916409/64139839-de9d9000-ce34-11e9-9e19-1f7bacde9d39.png)

**Comment by Jiahua-Gong** [comment]
I send the message FF. Sorry

**Comment by pkimelman-nxp** [comment]
What is FF?

**Comment by pkimelman-nxp** [comment]
> I send the message FF. Sorry

What is FF?

**Comment by Jiahua-Gong** [comment]
Read data from bus is FF,So the pad is open drain output. SDA_OE output is low.It's right.

**Comment by pkimelman-nxp** [comment]
OK, so I will close it. Thanks.
