### ISSUE TITLE
rtl file autonomous reg

### ISSUE THREAD

**Issue by Jiahua-Gong** [NXP/i3c-slave-design#16]
define the fbus_index 
```
reg [IDXMX:0]fbus_index;

....

always @(posedge clk_SCL or negedge RSTn)
  if(！RSTn)
     fbus <= 9'd0;


```
It's a problem.

**Comment by pkimelman-nxp** [comment]
In the update, I have it changed to:
      fbus_index        <= 0;
Which lets the tool sort it out. You can change your copy if you are having tools issues. At most a tool should only warn, and most seem to ignore this (right side larger than left).

define the fbus_index

reg [IDXMX:0]fbus_index;

....

always @(posedge clk_SCL or negedge RSTn)
  if(！RSTn)
     fbus <= 9'd0;




It's a problem,when i choose the local register mode(not use mr bus),it have too many problems.register number must less than 7.
