### ISSUE TITLE
MS Word errors in i3c_peripheral_slave_uarch.pdf

### ISSUE THREAD

**Issue by BurtHarris** [NXP/i3c-slave-design#6]
The architecture document has several broken links, which display as text "**Error! Reference source not found.**".   An example of this can be found on page 3 of the PDF file.   It appears that these are Microsoft Word references to figures in the document.

**Comment by pkimelman-nxp** [comment]
I believe those have all been fixed.

**Comment by BurtHarris** [comment]
👍
